<?xml version="1.0" encoding="utf-8"?>
<Project>

  <Import Project="$(SolutionDir)submodules/ChaosPresets.Targets/Properties/SetOs.targets" />
  <Import Project="$(SolutionDir)submodules/ChaosPresets.Targets/Paths/Output/Common.targets" />

  <PropertyGroup>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)'=='Windows'">
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(OS)'!='Windows'">
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>

</Project>
